language: objective-c
osx_image: xcode11.5
xcode_project: samples/Example/UZBroadcastDemo.xcodeproj
xcode_scheme: UZBroadcastDemo

script:
- cd samples/Example/
- travis_wait 30 pod install
- xcodebuild clean build -sdk iphonesimulator -workspace UZBroadcastDemo.xcworkspace -scheme UZBroadcastDemo CODE_SIGNING_REQUIRED=NO
