language: objective-c
osx_image: xcode11.5
xcode_project: samples/Example/UZBroadcastDemo.xcodeproj
xcode_scheme: UZBroadcastDemo

script:
- cd samples/Example/
- pod installi
- xcodebuild clean build -sdk iphonesimulator -workspace UZBroadcastDemo.xcworkspace -scheme UZBroadcastDemo CODE_SIGNING_REQUIRED=NO
#- xctool -project UZBroadcastDemo.xcodeproj -scheme 'UZBroadcastDemo' -configuration Release -sdk iphonesimulator -arch i386 build
