# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UZBroadcastExample' do
	platform :ios, '9.0'
	use_frameworks!
	pod 'UZBroadcast', :path => '../../.'
	
end
